<%-- 
    Author     : Alexander Patras
     
    
--%>

<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<html>
    <head>
        <%-- Include head section --%>
        <%@ include file="static/header.jsp" %>
        <title>CarMechanic - Περιγραφή</title>
    </head>
    <%
        //If logged in, get username
        String user = null;
        String uName = null;
        String userId = "4";
        String idsa = "4";
        if (session.getAttribute("user") != null) {
            user = (String) session.getAttribute("user");
            uName = (String) session.getAttribute("uName");
            userId = "" + (int) session.getAttribute("userId");
    %>
    <%@ include file="static/navbarloggedin.jsp" %>
    <% } else { %>
    <%@ include file="static/navbar.jsp" %>
    <% }%>
    <div class="panel panel-default center-block" style="width: 50%;">
        <ol class = "breadcrumb">
            <li><a href = "index.jsp">Αρχική</a></li>
            <li class="active">Περιγραφή - Αναφορά

            </li>

        </ol>
        <div class="panel-body container-fluid">
            <div class="row heading">
                <div class="col-md-4 logo center-block">
                    <div class="page-header center-block">
                        <h1 class='center-block'>CarMechanic <br><small>Report</small></h1>
                        <a href="http://am1120.ddns.net/report/CarMechanic.pdf">In case of wrong encoding click here for PDF</a>
                    </div>


                </div>

            </div>

            <div class="row main-content">

              
<p>Έ&chi;&epsilon;&iota; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &eta; &pi;&epsilon;&rho;&iota;&sigma;&sigma;ό&tau;&epsilon;&rho;&eta; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;&iota;&kappa;ό&tau;&eta;&tau;&alpha; &alpha;&pi;ό &alpha;&upsilon;&tau;ή&nu; &pi;&omicron;&upsilon; &gamma;&rho;ά&phi;&tau;&eta;&kappa;&epsilon; &sigma;&tau;&omicron; &epsilon;&gamma;&chi;&epsilon;&iota;&rho;ί&delta;&iota;&omicron; &chi;&rho;ή&sigma;&eta;&sigmaf;. &Pi;&iota;&omicron; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha;, έ&chi;&omicron;&upsilon;&nu; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί:</p>
<p>&nbsp;</p>
<ul>
<li>&Sigma;&epsilon; &kappa;ά&theta;&epsilon; &sigma;&epsilon;&lambda;ί&delta;&alpha;:
<ul>
<li>&Upsilon;&pi;ά&rho;&chi;&epsilon;&iota; &eta; Navigation Bar, &mu;&epsilon; 6 &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf; &gamma;&iota;&alpha; &mu;&eta; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf;:
<ul>
<li>&Alpha;&rho;&chi;&iota;&kappa;ή, &Pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf;, &Epsilon;&pi;&iota;&kappa;&omicron;&iota;&nu;&omega;&nu;ί&alpha;, &Sigma;ύ&nu;&delta;&epsilon;&sigma;&eta; &Chi;&rho;ή&sigma;&tau;&eta;, &Epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή &Chi;&rho;ή&sigma;&tau;&eta; (&Omicron;&delta;&eta;&gamma;&omicron;ύ&nu; &sigma;&epsilon; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&epsilon;&sigmaf; &sigma;&epsilon;&lambda;ί&delta;&epsilon;&sigmaf;)</li>
</ul>
</li>
<li>&Gamma;&iota;&alpha; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf;:
<ul>
<li>Ό&pi;&omega;&sigmaf; &gamma;&iota;&alpha; &mu;&eta; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf; &mu;&epsilon; &tau;&eta; &delta;&iota;&alpha;&phi;&omicron;&rho;ά ό&tau;&iota; &delta;&epsilon;&nu; &upsilon;&pi;ά&rho;&chi;&omicron;&upsilon;&nu; &omicron;&iota; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta;&sigmaf; &kappa;&alpha;&iota; &epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή&sigmaf; &kappa;&alpha;&iota; &sigma;&tau;&eta; &theta;έ&sigma;&eta; &tau;&omicron;&upsilon;&sigmaf; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; &mu;ή&nu;&upsilon;&mu;&alpha; &mu;&epsilon; &tau;&omicron; ό&nu;&omicron;&mu;&alpha; &tau;&omicron;&upsilon; &chi;&rho;ή&sigma;&tau;&eta; &tau;&omicron; &omicron;&pi;&omicron;ί&omicron; &epsilon;ί&nu;&alpha;&iota; έ&nu;&alpha; dropdown button, &mu;&epsilon; &delta;ύ&omicron; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf;: &Pi;&rho;&omicron;&phi;ί&lambda; &kappa;&alpha;&iota; &Alpha;&pi;&omicron;&sigma;ύ&nu;&delta;&epsilon;&sigma;&eta;</li>
</ul>
</li>
</ul>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>&Alpha;&rho;&chi;&iota;&kappa;ή &Sigma;&epsilon;&lambda;ί&delta;&alpha; (index.jsp &ndash; servlets/searchservlet.java):
<ul>
<li>&Alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon; &mu;&epsilon; &kappa;&epsilon;ί&mu;&epsilon;&nu;&omicron; ή &mu;&epsilon; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf;. &Alpha;&pi;ό &tau;&omicron; &kappa;&epsilon;ί&mu;&epsilon;&nu;&omicron; &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;&omicron;ύ&nu;&tau;&alpha;&iota; &mu;ό&nu;&omicron; &omicron;&iota; 2 &pi;&rho;ώ&tau;&epsilon;&sigmaf; &lambda;έ&xi;&epsilon;&iota;&sigmaf; &kappa;&alpha;&iota; &alpha;&gamma;&nu;&omicron;&omicron;ύ&nu;&tau;&alpha;&iota; ό&lambda;&epsilon;&sigmaf; &omicron;&iota; &upsilon;&pi;ό&lambda;&omicron;&iota;&pi;&epsilon;&sigmaf;. &Sigma;&tau;&iota;&sigmaf; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf;, &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;&pi;&iota;&lambda;&epsilon;&chi;&tau;&epsilon;ί &tau;&omicron;&upsilon;&lambda;ά&chi;&iota;&sigma;&tau;&omicron;&nu; &omicron; &laquo;&Kappa;&alpha;&tau;&alpha;&sigma;&kappa;&epsilon;&upsilon;&alpha;&sigma;&tau;ή&sigmaf;&raquo;.</li>
<li>&Tau;&alpha; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&alpha; &tau;&omega;&nu; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;ώ&nu; &pi;&rho;&omicron;έ&rho;&chi;&omicron;&nu;&tau;&alpha;&iota; &alpha;&pi;ό &tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;. &Kappa;&alpha;&tau;ά &tau;&eta; &phi;ό&rho;&tau;&omega;&sigma;&eta; &tau;&omicron;&upsilon; index.jsp, &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &mu;&epsilon; &chi;&rho;ή&sigma;&eta; &tau;&eta;&sigmaf; JSTL &gamma;&iota;&alpha; SQL queries. &Sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha; &alpha;&nu;&alpha;&zeta;&eta;&tau;&epsilon;ί &gamma;&iota;&alpha; &tau;&omicron;&upsilon;&sigmaf; &kappa;&alpha;&tau;&alpha;&sigma;&kappa;&epsilon;&upsilon;&alpha;&sigma;&tau;έ&sigmaf;, &kappa;&alpha;&iota; &laquo;&gamma;&epsilon;&mu;ί&zeta;&epsilon;&iota;&raquo; &tau;&iota;&sigmaf; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf; &gamma;&iota;&alpha; &tau;&omicron;&upsilon;&sigmaf; &kappa;&alpha;&tau;&alpha;&sigma;&kappa;&epsilon;&upsilon;&alpha;&sigma;&tau;έ&sigmaf;. &Alpha;&phi;&omicron;ύ &epsilon;&pi;&iota;&lambda;&epsilon;&gamma;&epsilon;ί έ&nu;&alpha;&sigmaf; &kappa;&alpha;&tau;&alpha;&sigma;&kappa;&epsilon;&upsilon;&alpha;&sigma;&tau;ή&sigmaf;, &kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;&iota;&alpha; JavaScript &sigma;&upsilon;&nu;ά&rho;&tau;&eta;&sigma;&eta;, &eta; &omicron;&pi;&omicron;ί&alpha; &mu;&epsilon; &tau;&eta; &sigma;&epsilon;&iota;&rho;ά &tau;&eta;&sigmaf; &kappa;&alpha;&lambda;&epsilon;ί &tau;&omicron; servlets/UpdateSearchPageSerlvet.java &delta;&upsilon;&nu;&alpha;&mu;&iota;&kappa;ά, &pi;&rho;&omicron;&kappa;&epsilon;&iota;&mu;έ&nu;&omicron;&upsilon; &nu;&alpha; &laquo;&gamma;&epsilon;&mu;ί&sigma;&omicron;&upsilon;&nu;&raquo; &omicron;&iota; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf; &tau;&omicron;&upsilon; &mu;&omicron;&nu;&tau;έ&lambda;&omicron;&upsilon;, &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&omicron;&nu; &kappa;&alpha;&tau;&alpha;&sigma;&kappa;&epsilon;&upsilon;&alpha;&sigma;&tau;ή. &Alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&eta; &epsilon;&nu;έ&rho;&gamma;&epsilon;&iota;&alpha; &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; &kappa;&alpha;&iota; &gamma;&iota;&alpha; &tau;&iota;&sigmaf; ά&lambda;&lambda;&epsilon;&sigmaf; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf;.</li>
<li>&Kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;έ&sigma;&alpha; &alpha;&pi;ό &tau;&omicron; searchservlet &mu;&iota;&alpha; &kappa;&alpha;&tau;ά&lambda;&lambda;&eta;&lambda;&eta; &mu;έ&theta;&omicron;&delta;&omicron;&sigmaf; &alpha;&pi;ό &tau;&eta; database/DatabaseManager.java, &alpha;&nu;ά&lambda;&omicron;&gamma;&alpha; &mu;&epsilon; &tau;&eta;&nu; &mu;έ&theta;&omicron;&delta;&omicron; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta;&sigmaf; &pi;&omicron;&upsilon; &epsilon;&pi;&iota;&lambda;έ&chi;&tau;&eta;&kappa;&epsilon;, &kappa;&alpha;&iota; &epsilon;&kappa;&tau;&epsilon;&lambda;&epsilon;ί&tau;&alpha;&iota; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;. &Tau;&alpha; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;έ&sigma;&mu;&alpha;&tau;&alpha; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&omicron;&nu;&tau;&alpha;&iota; &pi;ί&sigma;&omega; &sigma;&tau;&omicron; index.jsp, &kappa;&alpha;&iota; &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&omicron;&nu;&tau;&alpha;&iota; &sigma;&tau;&omicron; &kappa;ά&tau;&omega; &mu;έ&rho;&omicron;&sigmaf; &laquo;&Alpha;&pi;&omicron;&tau;&epsilon;&lambda;έ&sigma;&mu;&alpha;&tau;&alpha; &Alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta;&sigmaf;&raquo;. &Alpha;&nu; &delta;&epsilon;&nu; &beta;&rho;&epsilon;&theta;&omicron;ύ&nu; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;έ&sigma;&mu;&alpha;&tau;&alpha;, &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&tau;&alpha;&iota; &kappa;&epsilon;&nu;ό&sigmaf; &pi;ί&nu;&alpha;&kappa;&alpha;&sigmaf;.</li>
<li>&Delta;ί&pi;&lambda;&alpha; &alpha;&pi;ό &kappa;ά&theta;&epsilon; &alpha;&upsilon;&tau;&omicron;&kappa;ί&nu;&eta;&tau;&omicron; &sigma;&tau;&eta; &lambda;ί&sigma;&tau;&alpha; &alpha;&pi;&omicron;&tau;&epsilon;&lambda;&epsilon;&sigma;&mu;ά&tau;&omega;&nu; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; έ&nu;&alpha;&sigmaf; &upsilon;&pi;&epsilon;&rho;-&sigma;ύ&nu;&delta;&epsilon;&sigma;&mu;&omicron;&sigmaf; &laquo;Problems&raquo; &pi;&omicron;&upsilon; &omicron;&delta;&eta;&gamma;&epsilon;ί &sigma;&tau;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha; &laquo;&Pi;&rho;&omicron;&beta;&omicron;&lambda;ή &Alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon;&raquo; &gamma;&iota;&alpha; &tau;&omicron; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&omicron; &alpha;&upsilon;&tau;&omicron;&kappa;ί&nu;&eta;&tau;&omicron;. &Sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha; &kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &tau;&omicron; carview servlet &mu;&epsilon; ό&rho;&iota;&sigma;&mu;&alpha; &tau;&omicron; model id , &tau;&omicron;&upsilon; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon;.</li>
</ul>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>&Sigma;&epsilon;&lambda;ί&delta;&alpha; &Pi;&rho;&omicron;&beta;&omicron;&lambda;ή&sigmaf; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon; (carview.jsp &ndash; servlets/CarView.java):
<ul>
<li>&Eta; &sigma;&epsilon;&lambda;ί&delta;&alpha; &kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;έ&sigma;&omega; &tau;&omicron;&upsilon; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&omicron;&upsilon; servlet &mu;&epsilon; ό&rho;&iota;&sigma;&mu;&alpha; &ldquo;s&rdquo; &tau;&omicron; &alpha;&nu;&alpha;&gamma;&nu;&omega;&rho;&iota;&sigma;&tau;&iota;&kappa;&omicron;ύ &tau;&omicron;&upsilon; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon;. &Tau;&omicron; servlet &kappa;ά&nu;&epsilon;&iota; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &gamma;&iota;&alpha; &tau;&iota;&sigmaf; &alpha;&pi;&alpha;&rho;&alpha;ί&tau;&eta;&tau;&epsilon;&sigmaf; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; (&Pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &mu;&omicron;&nu;&tau;έ&lambda;&omicron;&upsilon;, &kappa;&alpha;&tau;&eta;&gamma;&omicron;&rho;ί&epsilon;&sigmaf; &pi;&rho;&omicron;&beta;&lambda;&eta;&mu;ά&tau;&omega;&nu; &kappa;&alpha;&iota; &tau;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha; &gamma;&iota;&alpha; &tau;&omicron; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&omicron; &mu;&omicron;&nu;&tau;έ&lambda;&omicron;) &kappa;&alpha;&iota; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&epsilon;&iota; &tau;&omicron; &alpha;&pi;&omicron;&tau;έ&lambda;&epsilon;&sigma;&mu;&alpha; &sigma;&tau;&omicron; carview.jsp.</li>
<li>&Omicron;&iota; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &gamma;&iota;&alpha; &tau;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha; &kappa;&alpha;&iota; &tau;&omicron; &mu;&omicron;&nu;&tau;έ&lambda;&omicron; &mu;&epsilon;&tau;&alpha;&phi;έ&rho;&omicron;&nu;&tau;&alpha;&iota; &mu;&epsilon; &chi;&rho;ή&sigma;&eta; Java Beans (model/Car.java, model/Problem.java, model/Category.java) &kappa;&alpha;&iota; &delta;&iota;&alpha;&beta;ά&zeta;&omicron;&nu;&tau;&alpha;&iota; &mu;&epsilon; &chi;&rho;ή&sigma;&eta; JSTL Core (for each tag) &kappa;&alpha;&iota; Expression Language (${beanname.attribute}).</li>
<li>&Epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&iota; &tau;&iota;&sigmaf; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &gamma;&iota;&alpha; &tau;&omicron; &mu;&omicron;&nu;&tau;έ&lambda;&omicron;, &mu;&iota;&alpha; &epsilon;&iota;&kappa;ό&nu;&alpha; placeholder &gamma;&iota;&alpha; &mu;&epsilon;&lambda;&lambda;&omicron;&nu;&tau;&iota;&kappa;ή &chi;&rho;ή&sigma;&eta;, έ&nu;&alpha; &kappa;&omicron;&upsilon;&mu;&pi;ί &pi;&omicron;&upsilon; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&epsilon;&iota; &pi;ί&sigma;&omega; &sigma;&tau;&eta;&nu; &alpha;&rho;&chi;&iota;&kappa;ή &kappa;&alpha;&iota; έ&nu;&alpha; &kappa;&omicron;&upsilon;&mu;&pi;ί &laquo;&Pi;&rho;&omicron;&sigma;&theta;ή&kappa;&eta; &Pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf;&raquo;, &tau;&omicron; &omicron;&pi;&omicron;ί&omicron; &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&tau;&alpha;&iota; &mu;ό&nu;&omicron; &sigma;&epsilon; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf;.</li>
<li>&Alpha;&pi;ό &kappa;ά&tau;&omega; &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&omicron;&nu;&tau;&alpha;&iota; &tau;&alpha; &kappa;&alpha;&tau;&alpha;&chi;&omega;&rho;&eta;&mu;έ&nu;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha; &gamma;&iota;&alpha; &tau;&omicron; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&omicron; &mu;&omicron;&nu;&tau;έ&lambda;&omicron; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon;. &Epsilon;ί&nu;&alpha;&iota; &chi;&omega;&rho;&iota;&sigma;&mu;έ&nu;&alpha; &sigma;&epsilon; &kappa;&alpha;&rho;&tau;έ&lambda;&epsilon;&sigmaf; &alpha;&nu;ά &kappa;&alpha;&tau;&eta;&gamma;&omicron;&rho;ί&alpha;.</li>
<li>&Delta;ί&pi;&lambda;&alpha; &alpha;&pi;ό &kappa;ά&theta;&epsilon; &pi;&rho;ό&beta;&lambda;&eta;&mu;&alpha;, &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; έ&nu;&alpha;&sigmaf; &upsilon;&pi;&epsilon;&rho;&sigma;ύ&nu;&delta;&epsilon;&sigma;&mu;&omicron;&sigmaf; &omicron; &omicron;&pi;&omicron;ί&omicron;&sigmaf; &omicron;&delta;&eta;&gamma;&epsilon;ί &sigma;&tau;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha; &laquo;&Pi;&rho;&omicron;&beta;&omicron;&lambda;ή &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf;&raquo;. &Sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha;, &kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;&epsilon; &mu;έ&theta;&omicron;&delta;&omicron; GET &mu;έ&sigma;&omega; &tau;&omicron;&upsilon; servlets/ProblewView.java &kappa;&alpha;&iota; &mu;&epsilon; ό&rho;&iota;&sigma;&mu;&alpha; &ldquo;s&rdquo; &tau;&omicron; ID &tau;&omicron;&upsilon; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf; &pi;&omicron;&upsilon; &epsilon;&pi;&iota;&lambda;έ&chi;&tau;&eta;&kappa;&epsilon;.</li>
</ul>
</li>
<li>&Sigma;&epsilon;&lambda;ί&delta;&alpha; &pi;&rho;&omicron;&beta;&omicron;&lambda;ή&sigmaf; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf; (problemview.jsp - servlets/ProblemView.java):
<ul>
<li>&Kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;έ&sigma;&omega; &tau;&omicron;&upsilon; servlet ProblemView.java, &tau;&omicron; &omicron;&pi;&omicron;ί&omicron; &kappa;ά&nu;&epsilon;&iota; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &gamma;&iota;&alpha; &tau;&iota;&sigmaf; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &tau;&omicron;&upsilon; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&omicron;&upsilon; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf;, &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&eta;&nu; &pi;&alpha;&rho;ά&mu;&epsilon;&tau;&rho;&omicron; (problem id) &mu;&epsilon; &tau;&eta;&nu; &omicron;&pi;&omicron;ί&alpha; &kappa;&alpha;&lambda;έ&sigma;&tau;&eta;&kappa;&epsilon;.</li>
<li>&Epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&iota; έ&nu;&alpha; &kappa;&epsilon;ί&mu;&epsilon;&nu;&omicron; &omega;&sigmaf; &tau;&eta;&nu; &pi;&epsilon;&rho;&iota;&gamma;&rho;&alpha;&phi;ή &tau;&omicron;&upsilon; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf;, &delta;&iota;ά&phi;&omicron;&rho;&epsilon;&sigmaf; &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;ί&epsilon;&sigmaf; (&sigma;&epsilon; &alpha;&upsilon;&tau;ή&nu; &tau;&eta;&nu; έ&kappa;&delta;&omicron;&sigma;&eta; &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&iota; &mu;ό&nu;&omicron; placeholders), &kappa;&omicron;&upsilon;&mu;&pi;&iota;ά &gamma;&iota;&alpha; &pi;&rho;&omicron;&sigma;&theta;ή&kappa;&eta; &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;&iota;ώ&nu; &kappa;&alpha;&iota; &lambda;ύ&sigma;&eta;&sigmaf; (&mu;ό&nu;&omicron; &gamma;&iota;&alpha; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf;), &tau;&eta; &lambda;ύ&sigma;&eta; &tau;&omicron;&upsilon; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf; &alpha;&nu; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; &kappa;&alpha;&iota; &tau;έ&lambda;&omicron;&sigmaf; &sigma;&chi;ό&lambda;&iota;&alpha; &tau;&omega;&nu; &chi;&rho;&eta;&sigma;&tau;ώ&nu; (&epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&omicron;&nu;&tau;&alpha;&iota; &mu;ό&nu;&omicron; &gamma;&iota;&alpha; &sigma;&upsilon;&nu;&delta;&epsilon;&delta;&epsilon;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf;).</li>
<li>&Eta; &pi;&rho;&omicron;&sigma;&theta;ή&kappa;&eta; &lambda;ύ&sigma;&eta;&sigmaf; &delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &sigma;&epsilon; &alpha;&upsilon;&tau;ή&nu; &tau;&eta;&nu; έ&kappa;&delta;&omicron;&sigma;&eta;.</li>
</ul>
</li>
<li>&Sigma;&epsilon;&lambda;ί&delta;&alpha; &epsilon;&iota;&sigma;&alpha;&gamma;&omega;&gamma;ή&sigmaf; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf; &gamma;&iota;&alpha; έ&nu;&alpha; &mu;&omicron;&nu;&tau;έ&lambda;&omicron; (insertproblem.jsp &ndash; serverlets/inserproblem.java):
<ul>
<li>Έ&chi;&epsilon;&iota; &delta;ύ&omicron; &pi;&epsilon;&delta;ί&alpha; &epsilon;&iota;&sigma;&alpha;&gamma;&omega;&gamma;ή&sigmaf; &kappa;&epsilon;&iota;&mu;έ&nu;&omicron;&upsilon;, &gamma;&iota;&alpha; &pi;&epsilon;&rho;&iota;&gamma;&rho;&alpha;&phi;ή &kappa;&alpha;&iota; &lambda;ύ&sigma;&eta; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf; &kappa;&alpha;&iota; &kappa;&omicron;&upsilon;&mu;&pi;ί &gamma;&iota;&alpha; &epsilon;&iota;&sigma;&alpha;&gamma;&omega;&gamma;ή (&mu;&iota;&alpha;&sigmaf; &mu;ό&nu;&omicron; &sigma;&epsilon; &alpha;&upsilon;&tau;ή&nu; &tau;&eta;&nu; έ&kappa;&delta;&omicron;&sigma;&eta;) &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;ί&alpha;&sigmaf;.</li>
<li>&Alpha;&phi;&omicron;ύ &pi;&alpha;&tau;&eta;&theta;&epsilon;ί &tau;&omicron; &kappa;&omicron;&upsilon;&mu;&pi;ί &laquo;&Alpha;&pi;&omicron;&theta;ή&kappa;&epsilon;&upsilon;&sigma;&eta;&raquo;, &alpha;&pi;&omicron;&sigma;&tau;έ&lambda;&lambda;&omicron;&nu;&tau;&alpha;&iota; &omicron;&iota; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &sigma;&tau;&omicron; insertproblem.java, &tau;&omicron; &omicron;&pi;&omicron;ί&omicron; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;ύ&epsilon;&iota; &tau;&omicron; &pi;&rho;ό&beta;&lambda;&eta;&mu;&alpha; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;, &kappa;&alpha;&iota; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&epsilon;&iota; &tau;&omicron; &chi;&rho;ή&sigma;&tau;&eta; &sigma;&tau;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha; &pi;&rho;&omicron;&beta;&omicron;&lambda;ή&sigmaf; &alpha;&upsilon;&tau;&omicron;&kappa;&iota;&nu;ή&tau;&omicron;&upsilon;.</li>
</ul>
</li>
<li>&Sigma;&epsilon;&lambda;ί&delta;&alpha; &pi;&rho;&omicron;&beta;&omicron;&lambda;ή&sigmaf; &pi;&rho;&omicron;&phi;ί&lambda; &chi;&rho;ή&sigma;&tau;&eta; (userprofile.jsp &ndash; servlets/UserProfile.java):
<ul>
<li>&Kappa;&alpha;&lambda;&epsilon;ί&tau;&epsilon; &mu;έ&sigma;&omega; &tau;&omicron;&upsilon; servlet, &mu;&epsilon; ό&rho;&iota;&sigma;&mu;&alpha; &tau;&omicron; &ldquo;id&rdquo; &tau;&omicron;&upsilon; &chi;&rho;ή&sigma;&tau;&eta;. &Tau;&omicron; servlet &alpha;&nu;&alpha;&zeta;&eta;&tau;&epsilon;ί &tau;&iota;&sigmaf; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &tau;&omicron;&upsilon; &chi;&rho;ή&sigma;&tau;&eta; &sigma;&tau;&eta; &beta;ά&sigma;&eta;, &kappa;&alpha;&iota; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&epsilon;&iota; &tau;&omicron; &alpha;&pi;&omicron;&tau;έ&lambda;&epsilon;&sigma;&mu;&alpha; &sigma;&tau;&omicron; userprofile.jsp.</li>
<li>&Epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&iota; &tau;&iota;&sigmaf; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;ί&epsilon;&sigmaf; &tau;&omicron;&upsilon; &chi;&rho;ή&sigma;&tau;&eta; &kappa;&alpha;&iota; &mu;&iota;&alpha; &epsilon;&iota;&kappa;ό&nu;&alpha; placeholder (&gamma;&iota;&alpha; &mu;&epsilon;&lambda;&lambda;&omicron;&nu;&tau;&iota;&kappa;ή &chi;&rho;ή&sigma;&eta;). &Delta;ί&pi;&lambda;&alpha; &alpha;&pi;ό &kappa;ά&theta;&epsilon; &pi;&epsilon;&delta;ί&omicron; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; έ&nu;&alpha; &kappa;&omicron;&upsilon;&mu;&pi;ί &epsilon;&pi;&epsilon;&xi;&epsilon;&rho;&gamma;&alpha;&sigma;ί&alpha;&sigmaf;. Ό&tau;&alpha;&nu; &pi;&alpha;&tau;&eta;&theta;&epsilon;ί &tau;&omicron; &kappa;&omicron;&upsilon;&mu;&pi;ί &epsilon;&pi;&epsilon;&xi;&epsilon;&rho;&gamma;&alpha;&sigma;ί&alpha;&sigmaf;, &alpha;&pi;ό &sigma;&tau;&alpha;&tau;&iota;&kappa;ό &kappa;&epsilon;ί&mu;&epsilon;&nu;&omicron;, &mu;&epsilon;&tau;&alpha;&tau;&rho;έ&pi;&epsilon;&tau;&alpha;&iota; &sigma;&epsilon; &pi;&epsilon;&delta;ί&omicron; &epsilon;&iota;&sigma;&alpha;&gamma;&omega;&gamma;ή&sigmaf; &kappa;&epsilon;&iota;&mu;έ&nu;&omicron;&upsilon;, &gamma;&iota;&alpha; &nu;&alpha; &epsilon;&iota;&sigma;&alpha;&chi;&theta;&epsilon;ί &eta; &alpha;&lambda;&lambda;&alpha;&gamma;ή.</li>
<li>&Tau;&omicron; &kappa;&omicron;&upsilon;&mu;&pi;ί &alpha;&pi;&omicron;&theta;ή&kappa;&epsilon;&upsilon;&sigma;&eta;, &sigma;&tau;έ&lambda;&nu;&epsilon;&iota; &tau;&iota;&sigmaf; &alpha;&lambda;&lambda;&alpha;&gamma;έ&sigmaf; &sigma;&tau;&omicron; servlet, &gamma;&iota;&alpha; &nu;&alpha; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;&upsilon;&tau;&omicron;ύ&nu; &sigma;&tau;&eta; &beta;ά&sigma;&eta;.</li>
<li>&Tau;&alpha; &kappa;&omicron;&upsilon;&mu;&pi;&iota;ά &kappa;ά&tau;&omega; &alpha;&pi;ό &tau;&eta;&nu; &epsilon;&iota;&kappa;ό&nu;&alpha; (&Epsilon;&pi;&epsilon;&xi;&epsilon;&rho;&gamma;&alpha;&sigma;ί&alpha; &amp; &delta;&iota;&alpha;&gamma;&rho;&alpha;&phi;ή) &epsilon;ί&nu;&alpha;&iota; &alpha;&nu;&epsilon;&nu;&epsilon;&rho;&gamma;ά.</li>
<li>&Sigma;&tau;&omicron; &kappa;ά&tau;&omega; &mu;έ&rho;&omicron;&sigmaf;, &phi;&alpha;ί&nu;&omicron;&nu;&tau;&alpha;&iota; &tau;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha; &pi;&omicron;&upsilon; έ&chi;&epsilon;&iota; &alpha;&pi;&omicron;&sigma;&tau;&epsilon;ί&lambda;&epsilon;&iota; &omicron; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&omicron;&sigmaf; &chi;&rho;ή&sigma;&tau;&eta;, &mu;&epsilon; &tau;&omicron;&nu; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&omicron; &sigma;ύ&nu;&delta;&epsilon;&sigma;&mu;&omicron; &pi;&rho;&omicron;&sigmaf; &alpha;&upsilon;&tau;ά.</li>
</ul>
</li>
<li>&Sigma;&epsilon;&lambda;ί&delta;&epsilon;&sigmaf; &lambda;ά&theta;&omicron;&upsilon;&sigmaf; &kappa;&alpha;&iota; 404,401 (errorPage.jsp, error-404.jsp,error-401jsp):
<ul>
<li>&Alpha;&nu; &tau;&upsilon;&chi;ό&nu; &epsilon;&iota;&sigma;ά&gamma;&omicron;&upsilon;&mu;&epsilon; &sigma;&tau;&eta; URL Address Bar &kappa;ά&pi;&omicron;&iota;&alpha; &delta;&iota;&epsilon;ύ&theta;&upsilon;&nu;&sigma;&eta; &pi;&omicron;&upsilon; &delta;&epsilon;&nu; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota;, &theta;&alpha; &omicron;&delta;&eta;&gamma;&eta;&theta;&omicron;ύ&mu;&epsilon; &sigma;&epsilon; &kappa;&alpha;&tau;ά&lambda;&lambda;&eta;&lambda;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha; &lambda;ά&theta;&omicron;&upsilon;&sigmaf;.</li>
<li>&Alpha;&nu; &sigma;&upsilon;&mu;&beta;&epsilon;ί &kappa;ά&pi;&omicron;&iota;&omicron; &lambda;ά&theta;&omicron;&sigmaf; &sigma;&tau;&iota;&sigmaf; JSP &sigma;&epsilon;&lambda;ί&delta;&epsilon;&sigmaf;, &omicron;&delta;&eta;&gamma;&omicron;ύ&mu;&alpha;&sigma;&tau;&epsilon; &sigma;&epsilon; &kappa;&alpha;&tau;ά&lambda;&lambda;&eta;&lambda;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha;.</li>
<li>&Gamma;&iota;&alpha; &tau;&iota;&sigmaf; &pi;&epsilon;&rho;&iota;&pi;&tau;ώ&sigma;&epsilon;&iota;&sigmaf; ά&rho;&nu;&eta;&sigma;&eta;&sigmaf; &pi;&rho;ό&sigma;&beta;&alpha;&sigma;&eta;&sigmaf; (401 pages) έ&chi;&epsilon;&iota; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &eta; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&eta; &sigma;&epsilon;&lambda;ί&delta;&alpha;, &alpha;&lambda;&lambda;ά &delta;&epsilon;&nu; &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;&epsilon;ί&tau;&alpha;&iota; &sigma;&epsilon; &alpha;&upsilon;&tau;ή&nu; &tau;&eta;&nu; έ&kappa;&delta;&omicron;&sigma;&eta;.</li>
</ul>
</li>
<li>&Sigma;&epsilon;&lambda;ί&delta;&alpha; &epsilon;&pi;&iota;&kappa;&omicron;&iota;&nu;&omega;&nu;ί&alpha;&sigmaf; (contact.jsp &ndash; servlets/SendMessage.java):
<ul>
<li>&Mu;&epsilon; &chi;&rho;ή&sigma;&eta; έ&tau;&omicron;&iota;&mu;&omega;&nu; &beta;&iota;&beta;&lambda;&iota;&omicron;&theta;&eta;&kappa;ώ&nu; έ&chi;&epsilon;&iota; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ή &mu;&eta;&nu;&upsilon;&mu;ά&tau;&omega;&nu; &alpha;&pi;ό &tau;&omicron;&upsilon;&sigmaf; &chi;&rho;ή&sigma;&tau;&epsilon;&sigmaf; &pi;&rho;&omicron;&sigmaf; &tau;&omicron; &delta;&iota;&alpha;&chi;&epsilon;&iota;&rho;&iota;&sigma;&tau;ή &tau;&eta;&sigmaf; &epsilon;&phi;&alpha;&rho;&mu;&omicron;&gamma;ή&sigmaf;, &mu;έ&sigma;&omega; email. &Sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha;, &mu;έ&sigma;&omega; &mu;&iota;&alpha; &phi;ό&rho;&mu;&alpha;&sigmaf; &pi;&omicron;&upsilon; &sigma;&upsilon;&mu;&pi;&lambda;&eta;&rho;ώ&nu;&epsilon;&iota; &omicron; &chi;&rho;ή&sigma;&tau;&eta;&sigmaf;, &sigma;&tau;έ&lambda;&nu;&epsilon;&tau;&epsilon; &sigma;&epsilon; &mu;&iota;&alpha; &pi;&rho;&omicron;&kappa;&alpha;&theta;&omicron;&rho;&iota;&sigma;&mu;έ&nu;&eta; &delta;&iota;&epsilon;ύ&theta;&upsilon;&nu;&sigma;&eta; &eta;&lambda;&epsilon;&kappa;&tau;&rho;&omicron;&nu;&iota;&kappa;&omicron;ύ &tau;&alpha;&chi;&upsilon;&delta;&rho;&omicron;&mu;&epsilon;ί&omicron;&upsilon;, &tau;&omicron; &mu;ή&nu;&upsilon;&mu;&alpha; &tau;&omicron;&upsilon; &chi;&rho;ή&sigma;&tau;&eta;.</li>
</ul>
</li>
</ul>
<p>&nbsp;</p>
<p>&Alpha;&upsilon;&tau;ά &pi;&omicron;&upsilon; &delta;&epsilon;&nu; έ&chi;&omicron;&upsilon;&nu; &upsilon;&lambda;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί, &mu;έ&chi;&rho;&iota; &kappa;&alpha;&iota; &tau;&eta; &sigma;&tau;&iota;&gamma;&mu;ή &tau;&eta;&sigmaf; &sigma;&upsilon;&gamma;&gamma;&rho;&alpha;&phi;ή&sigmaf; &alpha;&upsilon;&tau;ή&sigmaf; &tau;&eta;&sigmaf; &alpha;&nu;&alpha;&phi;&omicron;&rho;ά&sigmaf;:</p>
<ul>
<li>&Epsilon;&pi;&iota;&lambda;&omicron;&gamma;ή &kappa;&alpha;&tau;&eta;&gamma;&omicron;&rho;ί&alpha;&sigmaf; &kappa;&alpha;&tau;ά &tau;&eta;&nu; &epsilon;&iota;&sigma;&alpha;&gamma;&omega;&gamma;ή &epsilon;&nu;ό&sigmaf; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&omicron;&sigmaf;. &Tau;ώ&rho;&alpha; &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; &chi;&epsilon;&iota;&rho;&omicron;&kappa;ί&nu;&eta;&tau;&alpha; &sigma;&tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;.</li>
<li>&Delta;&epsilon; &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; &alpha;&pi;&omicron;&theta;ή&kappa;&epsilon;&upsilon;&sigma;&eta; &tau;&omega;&nu; &alpha;&lambda;&lambda;&alpha;&gamma;ώ&nu; &sigma;&tau;&omicron; &pi;&rho;&omicron;&phi;ί&lambda; &chi;&rho;ή&sigma;&tau;&eta; (&beta;&gamma;ά&zeta;&epsilon;&iota; &mu;ή&nu;&upsilon;&mu;&alpha; &lambda;ά&theta;&omicron;&upsilon;&sigmaf;).</li>
<li>&Beta;&epsilon;&lambda;&tau;ί&omega;&sigma;&eta; &tau;&omega;&nu; &gamma;&rho;&alpha;&phi;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &tau;&eta;&sigmaf; &alpha;&iota;&sigma;&theta;&eta;&tau;&iota;&kappa;ή&sigmaf;.</li>
<li>&Chi;&rho;ή&sigma;&eta; &phi;ί&lambda;&tau;&rho;&omega;&nu; &gamma;&iota;&alpha; &sigma;&kappa;&omicron;&pi;&omicron;ύ&sigmaf; &kappa;&alpha;&tau;&alpha;&gamma;&rho;&alpha;&phi;ή&sigmaf; &kappa;&alpha;&iota; &alpha;&sigma;&phi;ά&lambda;&epsilon;&iota;&alpha;&sigmaf; &sigma;&chi;&epsilon;&tau;&iota;&kappa;ά &mu;&epsilon; &tau;&eta; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta;/&epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή &chi;&rho;&eta;&sigma;&tau;ώ&nu;.</li>
<li>&Eta; &upsilon;&pi;&omicron;&sigma;&tau;ή&rho;&iota;&xi;&eta; &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;&iota;ώ&nu; &sigma;&tau;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha; &kappa;&alpha;&iota; &sigma;&tau;&omicron; &pi;&rho;&omicron;&phi;ί&lambda; &chi;&rho;ή&sigma;&tau;&eta; &delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &omicron;&lambda;&omicron;&kappa;&lambda;&eta;&rho;&omega;&mu;έ&nu;&eta;. &Upsilon;&pi;ά&rho;&chi;&epsilon;&iota; &kappa;ώ&delta;&iota;&kappa;&alpha;&sigmaf;, &alpha;&lambda;&lambda;ά &delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &omicron;&lambda;&omicron;&kappa;&lambda;&eta;&rho;&omega;&theta;&epsilon;ί</li>
<li>&Eta; &chi;&rho;ή&sigma;&eta; &pi;&alpha;&rho;&alpha;&mu;έ&tau;&rho;&omega;&nu; &alpha;&rho;&chi;&iota;&kappa;&omicron;&pi;&omicron;ί&eta;&sigma;&eta;&sigmaf; &tau;&omicron;&upsilon; Container. &Kappa;&upsilon;&rho;ί&omega;&sigmaf; &gamma;&iota;&alpha; &tau;&eta; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta; &mu;&epsilon; &tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;, &eta; &omicron;&pi;&omicron;ί&alpha; &kappa;&alpha;&lambda;&epsilon;ί&tau;&alpha;&iota; &sigma;&epsilon; &kappa;ά&theta;&epsilon; servlet. &Kappa;&alpha;&iota; &gamma;&iota;&alpha; &tau;&eta; &rho;ύ&theta;&mu;&iota;&sigma;&eta; &tau;&eta;&sigmaf; &delta;&iota;&alpha;&delta;&rho;&omicron;&mu;ή&sigmaf; &phi;&alpha;&kappa;έ&lambda;&omicron;&upsilon; &sigma;&tau;&omicron;&nu; &omicron;&pi;&omicron;ί&omicron; &theta;&alpha; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;ύ&omicron;&nu;&tau;&alpha;&iota; &omicron;&iota; &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;ί&epsilon;&sigmaf;.</li>
<li>&Eta; &chi;&rho;ή&sigma;&eta; &tau;&omega;&nu; &kappa;&alpha;&tau;&eta;&gamma;&omicron;&rho;&iota;ώ&nu; &tau;&omega;&nu; &pi;&rho;&omicron;&beta;&lambda;&eta;&mu;ά&tau;&omega;&nu; &sigma;&tau;&eta;&nu; &pi;&rho;&omicron;&beta;&omicron;&lambda;ή &tau;&omicron;&upsilon;&sigmaf; &sigma;&tau;&omicron; &pi;&rho;&omicron;&phi;ί&lambda; &chi;&rho;ή&sigma;&tau;&eta;.</li>
<li>&Eta; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta; &mu;&epsilon; &mu;έ&sigma;&alpha; &kappa;&omicron;&iota;&nu;&omega;&nu;&iota;&kappa;ή&sigmaf; &delta;&iota;&kappa;&tau;ύ&omega;&sigma;&eta;&sigmaf;.</li>
<li>&Eta; &delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;ί&alpha; &lambda;&omicron;&gamma;&alpha;&rho;&iota;&alpha;&sigma;&mu;&omicron;ύ &delta;&iota;&alpha;&chi;&epsilon;&iota;&rho;&iota;&sigma;&tau;ή, &gamma;&iota;&alpha; &chi;&epsilon;&iota;&rho;&iota;&sigma;&mu;ό &tau;&omicron;&upsilon; &pi;&epsilon;&rho;&iota;&epsilon;&chi;&omicron;&mu;έ&nu;&omicron;&upsilon; &mu;έ&sigma;&omega; &tau;&eta;&sigmaf; &epsilon;&phi;&alpha;&rho;&mu;&omicron;&gamma;ή&sigmaf; (&delta;&iota;&alpha;&gamma;&rho;&alpha;&phi;ή &pi;&rho;&omicron;&beta;&lambda;&eta;&mu;ά&tau;&omega;&nu;, &sigma;&chi;&omicron;&lambda;ί&omega;&nu; &kappa;&tau;&lambda;) &kappa;&alpha;&iota; &eta; &alpha;&nu;&tau;ί&sigma;&tau;&omicron;&iota;&chi;&eta; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;&iota;&kappa;ό&tau;&eta;&tau;&alpha;.</li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&Gamma;&iota;&alpha; &tau;&eta;&nu; &upsilon;&lambda;&omicron;&pi;&omicron;ί&eta;&sigma;&eta; &tau;&eta;&sigmaf; &epsilon;&phi;&alpha;&rho;&mu;&omicron;&gamma;ή&sigmaf; &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;ή&theta;&eta;&kappa;&alpha;&nu; &delta;&iota;ά&phi;&omicron;&rho;&epsilon;&sigmaf; &pi;&eta;&gamma;έ&sigmaf; &sigma;&tau;&omicron; &delta;&iota;&alpha;&delta;ί&kappa;&tau;&upsilon;&omicron; &kappa;&alpha;&iota; &tau;&omicron; &beta;&iota;&beta;&lambda;ί&omicron; &tau;&omicron;&upsilon; &mu;&alpha;&theta;ή&mu;&alpha;&tau;&omicron;&sigmaf;. &Pi;&iota;&omicron; &sigma;&upsilon;&gamma;&kappa;&epsilon;&kappa;&rho;&iota;&mu;έ&nu;&alpha;, &eta; &pi;&lambda;&epsilon;&iota;&omicron;&psi;&eta;&phi;ί&alpha; &tau;&omega;&nu; &pi;&lambda;&eta;&rho;&omicron;&phi;&omicron;&rho;&iota;ώ&nu; &kappa;&alpha;&iota; &tau;&omega;&nu; &pi;&alpha;&rho;&alpha;&delta;&epsilon;&iota;&gamma;&mu;ά&tau;&omega;&nu; &kappa;ώ&delta;&iota;&kappa;&alpha; &pi;&rho;&omicron;ή&rho;&theta;&alpha;&nu; &alpha;&pi;ό:</p>
<ul>
<li>http://stackoverflow.com</li>
<li>http://w3schools.com</li>
<li><a href="http://www.tutorialspoint.com/jsp">http://www.tutorialspoint.com/jsp</a></li>
<li><a href="http://theopentutorials.com/tutorials/java/design-patterns/post-redirect-get-prg-pattern-in-servlet-jsp/">http://theopentutorials.com/tutorials/java/design-patterns/post-redirect-get-prg-pattern-in-servlet-jsp/</a> (&tau;&rho;ό&pi;&omicron;&sigmaf; &gamma;&iota;&alpha; &alpha;&pi;&omicron;&phi;&upsilon;&gamma;ή &sigma;&phi;&alpha;&lambda;&mu;ά&tau;&omega;&nu; &pi;&omicron;&lambda;&lambda;&alpha;&pi;&lambda;ώ&nu; &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ώ&nu; &ndash; &delta;&epsilon;&nu; &epsilon;&phi;&alpha;&rho;&mu;ό&sigma;&tau;&eta;&kappa;&epsilon; &alpha;&kappa;ό&mu;&alpha; [&beta;&lambda;. servlets/searchresultsservlet.java])</li>
<li><a href="http://stackoverflow.com/questions/19448316/responsive-images-inline-block-in-a-div-with-bootstrap">http://stackoverflow.com/questions/19448316/responsive-images-inline-block-in-a-div-with-bootstrap</a> (&tau;&rho;ό&pi;&omicron;&sigmaf; &gamma;&iota;&alpha; &epsilon;&mu;&phi;ά&nu;&iota;&sigma;&eta; &tau;&omega;&nu; &phi;&omega;&tau;&omicron;&gamma;&rho;&alpha;&phi;&iota;ώ&nu; &sigma;&tau;&alpha; &pi;&rho;&omicron;&beta;&lambda;ή&mu;&alpha;&tau;&alpha;)</li>
<li><a href="http://www.oracle.com/technetwork/java/javase/jaf-136260.html">http://www.oracle.com/technetwork/java/javase/jaf-136260.html</a> (&gamma;&iota;&alpha; &tau;&eta;&nu; &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ή &tau;&omega;&nu; emails)</li>
<li><a href="https://java.net/projects/javamail/pages/Home">https://java.net/projects/javamail/pages/Home</a> (&gamma;&iota;&alpha; &tau;&eta;&nu; &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ή &tau;&omega;&nu; emails)</li>
<li><a href="http://getbootstrap.com">http://getbootstrap.com</a></li>
</ul>
<p>&nbsp;</p>
<p>&Kappa;ά&pi;&omicron;&iota;&alpha; &alpha;&pi;ό &tau;&alpha; &beta;&alpha;&sigma;&iota;&kappa;ά &epsilon;&rho;&gamma;&alpha;&lambda;&epsilon;ί&alpha; &pi;&omicron;&upsilon; &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;ή&theta;&eta;&kappa;&alpha;&nu;:</p>
<ul>
<li>JSTL - MySQL and Core libraries</li>
<li>Expression Language</li>
<li>Java Beans, used with EL</li>
<li>JQuery (JavaScript Library)</li>
<li>Bootstrap Framework (&gamma;&iota;&alpha; &tau;&omicron; &alpha;&iota;&sigma;&theta;&eta;&tau;&iota;&kappa;ό &kappa;&omicron;&mu;&mu;ά&tau;&iota;)</li>
<li>JAF &amp; JavaMail (&gamma;&iota;&alpha; &upsilon;&pi;&omicron;&sigma;&tau;ή&rho;&iota;&xi;&eta; &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ή&sigmaf; email)</li>
<li>UTH LDAP (UserManagement &alpha;&pi;ό 5<sup>&eta;</sup> &Epsilon;&rho;&gamma;&alpha;&sigma;ί&alpha;)</li>
<li>MD5 Hash Function (&gamma;&iota;&alpha; &alpha;&pi;&omicron;&theta;ή&kappa;&epsilon;&upsilon;&sigma;&eta; &tau;&omega;&nu; &tau;&omicron;&pi;&iota;&kappa;ώ&nu; &kappa;&omega;&delta;&iota;&kappa;ώ&nu;)</li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&Sigma;&eta;&mu;&epsilon;&iota;ώ&sigma;&epsilon;&iota;&sigmaf; &upsilon;&lambda;&omicron;&pi;&omicron;ί&eta;&sigma;&eta;&sigmaf;:</p>
<ul>
<li>Ό&lambda;&epsilon;&sigmaf; &omicron;&iota; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;ί&epsilon;&sigmaf; &gamma;&iota;&alpha; &tau;&eta; &beta;ά&sigma;&eta; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;, &beta;&rho;ί&sigma;&kappa;&omicron;&nu;&tau;&alpha;&iota; &sigma;&tau;&omicron; database/DatabaseManager.java. &Eta; &beta;ά&sigma;&eta; &epsilon;ί&nu;&alpha;&iota; MySQL.</li>
<li>&Sigma;&epsilon; &kappa;ά&theta;&epsilon; JSP, &gamma;ί&nu;&epsilon;&tau;&alpha;&iota; static include &tau;&omicron; &kappa;&omicron;&mu;&mu;ά&tau;&iota; &tau;&omicron;&upsilon; header (navigation bar etc) &kappa;&alpha;&iota; &tau;&alpha; JavaScript &pi;&omicron;&upsilon; &chi;&rho;&epsilon;&iota;ά&zeta;&omicron;&nu;&tau;&alpha;&iota;, &sigma;&tau;&omicron; &tau;έ&lambda;&omicron;&sigmaf; &tau;&omicron;&upsilon; body. &Beta;&rho;ί&sigma;&kappa;&omicron;&nu;&tau;&alpha;&iota; &sigma;&tau;&omicron; web/static/.</li>
<li>&Upsilon;&pi;ά&rho;&chi;&omicron;&upsilon;&nu; 3 JSP &sigma;&tau;&omicron; web/static/ &pi;&omicron;&upsilon; &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;&omicron;ύ&nu;&tau;&alpha;&iota; &alpha;&pi;ό &tau;&omicron; index.jsp, &mu;έ&sigma;&omega; &tau;&eta;&sigmaf; JavaScript &sigma;&upsilon;&nu;ά&rho;&tau;&eta;&sigma;&eta;&sigmaf;, &gamma;&iota;&alpha; &tau;&eta;&nu; &pi;&alpha;&rho;&alpha;&gamma;&omega;&gamma;ή &tau;&omicron;&upsilon; &pi;&epsilon;&rho;&iota;&epsilon;&chi;&omicron;&mu;έ&nu;&omicron;&upsilon; &gamma;&iota;&alpha; &tau;&iota;&sigmaf; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;έ&sigmaf; &alpha;&nu;&alpha;&zeta;ή&tau;&eta;&sigma;&eta;&sigmaf;, &alpha;&pi;ό &tau;&omicron; UpdateSearchPageServlet.</li>
</ul>
            </div>
        </div>
    </div>



    <%-- Include nessecary scripts --%>
    <%@ include file="static/endbody.jsp" %>

</html>
